site_name: Astubot
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - search

nav:
  - Home: index.md
  - About: about.md
  - MVP: mvp.md

extra_css:
  - styles.css

markdown_extensions:
  - toc:
      permalink: true

